-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'PAYROLL_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'INVOICE_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE 'SYSTEM';

-- AlterEnum
ALTER TYPE "AppSettingKey" ADD VALUE 'COMPANY_PROFILE';
ALTER TYPE "AppSettingKey" ADD VALUE 'LEAVE_POLICY';
ALTER TYPE "AppSettingKey" ADD VALUE 'NOTIFICATION_SETTINGS';
